version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "domengabrovsek"
    reviewers:
      - "domengabrovsek"
    target-branch: "master"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "domengabrovsek"
    reviewers:
      - "domengabrovsek"
    target-branch: "master"