name: Build Docker images

on:
  push:
    branches:
      - master

jobs:

  # Build and push Docker image for x86_64 architecture
  build-default-image:
  name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: domengabrovsek
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: domengabrovsek/crypto-dashboard-server:latest

  # Build and push Docker image for Raspberry Pi architecture
  build-rpi-image:
    name: Build and push Docker image on Raspberry Pi
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: domengabrovsek
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: domengabrovsek/crypto-dashboard-server:rpi-latest
