name: Build and Push Docker Image for RPi

on:
  push:
    branches:
      - master 

jobs:
  build-and-push:
    name: Build and push Docker image on Raspberry Pi
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: domengabrovsek
          password: ${{ secrets.DOCKER_HUB_ACCES_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: domengabrovsek/crypto-dashboard-server:rpi-latest
