name: Pull request - General workflow

env:
  NODE_VERSION: 18

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION}}

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-progress --audit=false

      - name: Run linter
        run: npm run lint

  # run build 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION}}

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-progress --audit=false

      - name: Run build
        run: npm run build